
using System.Windows.Media.Media3D;

#region AutoGeneratedHeader
// nabr :: Cell.cs last updated by: Ryan Hughes
// File last updated at: 20:02:42 on 12-02-2025
// Parent solution for file: nabr, file originally created at 20:02:41 on 12-02-2025 as part of project Nabr.
#endregion

namespace Nabr.Layout {
	public class Cell {
		public Point3D Position { get; set; }
		public string UnitType { get; set; }
		public double Width { get; set; }
		public double Length { get; set; }
		public string LayoutElementType { get; set; }

		public Cell() {
			UnitType = "full";
			Width = 8.0;
			Length = 8.5;
			LayoutElementType = "default";

			GlobalLogger.AddDebug("New default instance of Cell created.");
		}

		public Cell(string unitType = "full", double width = 8.0, double length = 8.5, string layoutElementType = "empty") {
			UnitType = unitType;
			Width = width;
			Length = length;
			LayoutElementType = layoutElementType;

			GlobalLogger.AddDebug($"New instance of Cell created with Unit Type: {unitType}, Width: {width}, Length {length} and Layout Element Type: {layoutElementType}");
		}

		public override string ToString() => $"Unit Type: {UnitType}, Width: {Width}, Length: {Length}, Layout Element Type: {LayoutElementType}";
	}
}
