using System.Collections.Generic;
using System.Linq;

#region AutoGeneratedHeader
// nabr :: Mix.cs last updated by: Ryan Hughes
// File last updated at: 20:02:23 on 12-02-2025
// Parent solution for file: nabr, file originally created at 20:02:22 on 12-02-2025 as part of project Nabr.
#endregion

namespace Nabr.Layout {
	public class Mix {
		private readonly Dictionary<string, double> _cellDensities = new();

		public Mix(List<string> type, List<double> density) { }

		public void AddCellType(string cellType, double density) {
			if (density is < 0 or > 1) {
				GlobalLogger.AddLog($"{cellType} density must be between 0 and 1.");
			}

			if (_cellDensities.Values.Sum() + density > 1) {
				GlobalLogger.AddLog("Total density cannot exceed 1.0.");
			}

			_cellDensities[cellType] = density;
		}

		public double GetDensity(string cellType) => _cellDensities.GetValueOrDefault(cellType, 0);

		public IReadOnlyDictionary<string, double> GetAllDensities() => _cellDensities;

		public override string ToString() => System.String.Join(", ", _cellDensities.Select(kvp => $"{kvp.Key}: {kvp.Value}"));
	}
}