
using System;
using System.Collections.Generic;

#region AutoGeneratedHeader
// nabr :: Logs.cs last updated by: Ryan Hughes
// File last updated at: 20:02:37 on 12-02-2025
// Parent solution for file: nabr, file originally created at 20:02:36 on 12-02-2025 as part of project Nabr.
#endregion

namespace Nabr {
	public static class GlobalLogger {
		private static readonly List<string> Log = new();

		public static void AddLog(string message) => Log.Add(message);

		public static void AddDebug(string message) => Log.Add("[DEBUG]: " + message);

		public static IEnumerable<string> GetLogs() => Log;
	}

	public class Core {
		public Core() {
			GlobalLogger.AddLog($"New instance of Nabr Core created at {DateTime.Now.ToShortTimeString()}");
		}
	}
}